.if !defined(_CONFIT_HOST_MK_)
_CONFIT_HOST_MK_=1

CONFIT_BIN_ROOT=${CONFIT_OBJROOT}/bin
CONFIT_OBJ_ROOT=${CONFIT_OBJROOT}/obj
CONFIT_TEST_BIN_ROOT=${CONFIT_OBJROOT}/tests/bin
CONFIT_BINARY=${CONFIT_BIN_ROOT}/confit

CONFIT_STRICT_CFLAGS= \
	-std=c17 -Wall -Wextra -Werror -pedantic
CONFIT_INCLUDE_FLAGS= \
	-I${CONFIT_SOURCE_ROOT}/include \
	-I${CONFIT_SOURCE_ROOT}/src/parser \
	-I${CONFIT_SOURCE_ROOT}/src/model/v2 \
	-I${CONFIT_SOURCE_ROOT}/src/schema \
	-I${CONFIT_SOURCE_ROOT}/src/expression/v2 \
	-I${CONFIT_SOURCE_ROOT}/vendor/tomlc17 \
	-I${CONFIT_SOURCE_ROOT}/tests/support

CONFIT_LINK_LIBS=

CONFIT_PRODUCT_SOURCES= \
	${CONFIT_CORE_SOURCES} \
	${CONFIT_HOST_SOURCES} \
	${CONFIT_PARSER_SOURCES} \
	${CONFIT_MODEL_AND_SCHEMA_SOURCES} \
	${CONFIT_EXPRESSION_AND_CONSTRAINT_SOURCES} \
	${CONFIT_RESOLVER_SOURCES} \
	${CONFIT_GENERATOR_SOURCES}

CONFIT_TEST_SOURCES= \
	${CONFIT_UNIT_TEST_SOURCES} \
	${CONFIT_FUZZ_TEST_SOURCES} \
	${CONFIT_INTEGRATION_TEST_SOURCES}

CONFIT_PRODUCT_OBJECTS=
CONFIT_CLI_OBJECTS=
CONFIT_TEST_SUPPORT_OBJECTS=
CONFIT_TEST_OBJECTS=
CONFIT_TEST_BINARIES=
CONFIT_DEPFILES=

CONFIT_BUILD_DEFINES= \
	-DCONFIT_BUILD_MODE=\"bmake\" \
	-DCONFIT_BUILD_C_COMPILER_ID=\"c17-probed\" \
	-DCONFIT_BUILD_C_COMPILER_VERSION=\"external\" \
	-DCONFIT_BUILD_SYSTEM_NAME=\"${.MAKE.OS}\"

CONFIT_TEST_DEFINES= \
	-DCONFIT_TEST_SOURCE_DIR=\"${CONFIT_SOURCE_ROOT}\"

.for _src in ${CONFIT_PRODUCT_SOURCES}
_obj=${CONFIT_OBJ_ROOT}/${_src:R}.o
CONFIT_PRODUCT_OBJECTS+=${CONFIT_OBJ_ROOT}/${_src:R}.o
CONFIT_DEPFILES+=${CONFIT_OBJ_ROOT}/${_src:R}.d
${_obj}: ${CONFIT_SOURCE_ROOT}/${_src}
	@mkdir -p -- ${.TARGET:H}
.if ${_src} == "vendor/tomlc17/tomlc17.c"
	${CONFIT_HOST_CC} -std=c17 -w ${CONFIT_INCLUDE_FLAGS} -MMD -MP \
	    -MF ${.TARGET:R}.d -c ${CONFIT_SOURCE_ROOT}/${_src} -o ${.TARGET}
.else
	${CONFIT_HOST_CC} ${CONFIT_STRICT_CFLAGS} ${CONFIT_INCLUDE_FLAGS} \
	    -MMD -MP -MF ${.TARGET:R}.d -c ${CONFIT_SOURCE_ROOT}/${_src} -o ${.TARGET}
.endif
.endfor

.for _src in ${CONFIT_CLI_SOURCES}
_obj=${CONFIT_OBJ_ROOT}/${_src:R}.o
CONFIT_CLI_OBJECTS+=${CONFIT_OBJ_ROOT}/${_src:R}.o
CONFIT_DEPFILES+=${CONFIT_OBJ_ROOT}/${_src:R}.d
${_obj}: ${CONFIT_SOURCE_ROOT}/${_src}
	@mkdir -p -- ${.TARGET:H}
	${CONFIT_HOST_CC} ${CONFIT_STRICT_CFLAGS} ${CONFIT_INCLUDE_FLAGS} \
	    ${CONFIT_BUILD_DEFINES} -MMD -MP -MF ${.TARGET:R}.d \
	    -c ${CONFIT_SOURCE_ROOT}/${_src} -o ${.TARGET}
.endfor

.for _src in ${CONFIT_TEST_SUPPORT_SOURCES}
_obj=${CONFIT_OBJ_ROOT}/${_src:R}.o
CONFIT_TEST_SUPPORT_OBJECTS+=${CONFIT_OBJ_ROOT}/${_src:R}.o
CONFIT_DEPFILES+=${CONFIT_OBJ_ROOT}/${_src:R}.d
${_obj}: ${CONFIT_SOURCE_ROOT}/${_src}
	@mkdir -p -- ${.TARGET:H}
	${CONFIT_HOST_CC} ${CONFIT_STRICT_CFLAGS} ${CONFIT_INCLUDE_FLAGS} \
	    -MMD -MP -MF ${.TARGET:R}.d -c ${CONFIT_SOURCE_ROOT}/${_src} -o ${.TARGET}
.endfor

.for _src in ${CONFIT_TEST_SOURCES}
_obj=${CONFIT_OBJ_ROOT}/${_src:R}.o
_bin=${CONFIT_TEST_BIN_ROOT}/confit_${_src:T:R}
CONFIT_TEST_OBJECTS+=${CONFIT_OBJ_ROOT}/${_src:R}.o
CONFIT_TEST_BINARIES+=${CONFIT_TEST_BIN_ROOT}/confit_${_src:T:R}
CONFIT_DEPFILES+=${CONFIT_OBJ_ROOT}/${_src:R}.d
${_obj}: ${CONFIT_SOURCE_ROOT}/${_src}
	@mkdir -p -- ${.TARGET:H}
	${CONFIT_HOST_CC} ${CONFIT_STRICT_CFLAGS} ${CONFIT_INCLUDE_FLAGS} \
	    ${CONFIT_TEST_DEFINES} -MMD -MP -MF ${.TARGET:R}.d \
	    -c ${CONFIT_SOURCE_ROOT}/${_src} -o ${.TARGET}
${_bin}: ${_obj} ${CONFIT_PRODUCT_OBJECTS} ${CONFIT_TEST_SUPPORT_OBJECTS}
	@mkdir -p -- ${.TARGET:H}
	${CONFIT_HOST_CC} -o ${.TARGET} ${.ALLSRC} ${CONFIT_LINK_LIBS}
.endfor

${CONFIT_BINARY}: ${CONFIT_PRODUCT_OBJECTS} ${CONFIT_CLI_OBJECTS}
	@mkdir -p -- ${.TARGET:H}
	${CONFIT_HOST_CC} -o ${.TARGET} ${.ALLSRC} ${CONFIT_LINK_LIBS}

CONFIT_GENERATED_FILES= \
	${CONFIT_PRODUCT_OBJECTS} ${CONFIT_CLI_OBJECTS} \
	${CONFIT_TEST_SUPPORT_OBJECTS} ${CONFIT_TEST_OBJECTS} \
	${CONFIT_DEPFILES} ${CONFIT_BINARY} ${CONFIT_TEST_BINARIES}

# Test source path마다 고유 target을 parse time에 만든다. 각 recipe는 한 C executable만
# 실행하며 shell loop나 runtime registry가 test selection을 소유하지 않는다.
CONFIT_DIRECT_TEST_TARGETS=
.for _test_binary in ${CONFIT_TEST_BINARIES}
CONFIT_DIRECT_TEST_TARGETS+=run-${_test_binary:T}
.PHONY: run-${_test_binary:T}
run-${_test_binary:T}: ${_test_binary}
	@${_test_binary}
.endfor

.for _dep in ${CONFIT_DEPFILES}
.sinclude "${_dep}"
.endfor

.endif
