.if !defined(_CONFIT_HOST_MK_)
_CONFIT_HOST_MK_=1

CONFIT_BIN_ROOT=${CONFIT_OBJROOT}/bin
CONFIT_OBJ_ROOT=${CONFIT_OBJROOT}/obj
CONFIT_TEST_BIN_ROOT=${CONFIT_OBJROOT}/tests/bin
CONFIT_BINARY=${CONFIT_BIN_ROOT}/confit

CONFIT_STRICT_CFLAGS= \
	-std=c17 -Wall -Wextra -Werror -pedantic
.if ${CONFIT_HOST_CC_FAMILY} == "clang" && ${.MAKE.OS} == "Darwin"
CONFIT_STRICT_CFLAGS+= \
	-Wno-availability -Wno-extra-semi -Wno-expansion-to-defined \
	-Wno-nullability-completeness -Wno-nullability-extension
.elif ${CONFIT_HOST_CC_FAMILY} == "gcc"
CONFIT_STRICT_CFLAGS+=-Wno-format-truncation
.endif
CONFIT_INCLUDE_FLAGS= \
	-I${CONFIT_SOURCE_ROOT}/include \
	-I${CONFIT_SOURCE_ROOT}/src/parser \
	-I${CONFIT_SOURCE_ROOT}/src/model/v2 \
	-I${CONFIT_SOURCE_ROOT}/src/schema \
	-I${CONFIT_SOURCE_ROOT}/src/expression/v2 \
	-I${CONFIT_SOURCE_ROOT}/vendor/tomlc17 \
	-I${CONFIT_SOURCE_ROOT}/tests/support

.if ${CONFIT_ENABLE_TUI} == "yes"
CONFIT_SELECTED_TUI_SOURCES=${CONFIT_TUI_SOURCES}
CONFIT_HAS_CURSES=1
CONFIT_LINK_LIBS=-lcurses
.else
CONFIT_SELECTED_TUI_SOURCES=${CONFIT_TUI_UNSUPPORTED_SOURCES}
CONFIT_HAS_CURSES=0
CONFIT_LINK_LIBS=
.endif

CONFIT_PRODUCT_SOURCES= \
	${CONFIT_CORE_SOURCES} \
	${CONFIT_HOST_SOURCES} \
	${CONFIT_PARSER_SOURCES} \
	${CONFIT_MODEL_AND_SCHEMA_SOURCES} \
	${CONFIT_EXPRESSION_AND_CONSTRAINT_SOURCES} \
	${CONFIT_RESOLVER_SOURCES} \
	${CONFIT_GENERATOR_AND_COMPAT_SOURCES} \
	${CONFIT_SELECTED_TUI_SOURCES}

CONFIT_TEST_SOURCES= \
	${CONFIT_UNIT_TEST_SOURCES} \
	${CONFIT_FUZZ_TEST_SOURCES} \
	${CONFIT_INTEGRATION_TEST_SOURCES}

CONFIT_PRODUCT_OBJECTS=
CONFIT_CLI_OBJECTS=
CONFIT_TEST_SUPPORT_OBJECTS=
CONFIT_TEST_OBJECTS=
CONFIT_TEST_BINARIES=
CONFIT_DEPFILES=

CONFIT_BUILD_DEFINES= \
	-DCONFIT_BUILD_MODE=\"bmake\" \
	-DCONFIT_BUILD_C_COMPILER_ID=\"${CONFIT_HOST_CC_FAMILY}\" \
	-DCONFIT_BUILD_C_COMPILER_VERSION=\"external\" \
	-DCONFIT_BUILD_HAS_CURSES=${CONFIT_HAS_CURSES} \
	-DCONFIT_BUILD_SYSTEM_NAME=\"${.MAKE.OS}\"

CONFIT_TEST_DEFINES= \
	-DCONFIT_TEST_SOURCE_DIR=\"${CONFIT_SOURCE_ROOT}\" \
	-DCONFIT_TEST_HAS_TUI=${CONFIT_HAS_CURSES} \
	-DCONFIT_TEST_CMAKE_EXECUTABLE=\"${CONFIT_LEGACY_CMAKE}\"

.if !empty(CONFIT_QSTAR)
CONFIT_TEST_DEFINES+=-DCONFIT_TEST_QSTAR_EXECUTABLE=\"${CONFIT_QSTAR}\"
.endif

.for _src in ${CONFIT_PRODUCT_SOURCES}
_obj=${CONFIT_OBJ_ROOT}/${_src:R}.o
CONFIT_PRODUCT_OBJECTS+=${CONFIT_OBJ_ROOT}/${_src:R}.o
CONFIT_DEPFILES+=${CONFIT_OBJ_ROOT}/${_src:R}.d
${_obj}: ${CONFIT_SOURCE_ROOT}/${_src}
	@mkdir -p -- ${.TARGET:H}
.if ${_src} == "vendor/tomlc17/tomlc17.c"
	${CONFIT_HOST_CC} -std=c17 -w ${CONFIT_INCLUDE_FLAGS} -MMD -MP \
	    -MF ${.TARGET:R}.d -c ${.ALLSRC} -o ${.TARGET}
.else
	${CONFIT_HOST_CC} ${CONFIT_STRICT_CFLAGS} ${CONFIT_INCLUDE_FLAGS} \
	    -MMD -MP -MF ${.TARGET:R}.d -c ${.ALLSRC} -o ${.TARGET}
.endif
.endfor

.for _src in ${CONFIT_CLI_SOURCES}
_obj=${CONFIT_OBJ_ROOT}/${_src:R}.o
CONFIT_CLI_OBJECTS+=${CONFIT_OBJ_ROOT}/${_src:R}.o
CONFIT_DEPFILES+=${CONFIT_OBJ_ROOT}/${_src:R}.d
${_obj}: ${CONFIT_SOURCE_ROOT}/${_src}
	@mkdir -p -- ${.TARGET:H}
	${CONFIT_HOST_CC} ${CONFIT_STRICT_CFLAGS} ${CONFIT_INCLUDE_FLAGS} \
	    ${CONFIT_BUILD_DEFINES} -MMD -MP -MF ${.TARGET:R}.d \
	    -c ${.ALLSRC} -o ${.TARGET}
.endfor

.for _src in ${CONFIT_TEST_SUPPORT_SOURCES}
_obj=${CONFIT_OBJ_ROOT}/${_src:R}.o
CONFIT_TEST_SUPPORT_OBJECTS+=${CONFIT_OBJ_ROOT}/${_src:R}.o
CONFIT_DEPFILES+=${CONFIT_OBJ_ROOT}/${_src:R}.d
${_obj}: ${CONFIT_SOURCE_ROOT}/${_src}
	@mkdir -p -- ${.TARGET:H}
	${CONFIT_HOST_CC} ${CONFIT_STRICT_CFLAGS} ${CONFIT_INCLUDE_FLAGS} \
	    -MMD -MP -MF ${.TARGET:R}.d -c ${.ALLSRC} -o ${.TARGET}
.endfor

.for _src in ${CONFIT_TEST_SOURCES}
_obj=${CONFIT_OBJ_ROOT}/${_src:R}.o
_bin=${CONFIT_TEST_BIN_ROOT}/confit_${_src:T:R}
CONFIT_TEST_OBJECTS+=${CONFIT_OBJ_ROOT}/${_src:R}.o
CONFIT_TEST_BINARIES+=${CONFIT_TEST_BIN_ROOT}/confit_${_src:T:R}
CONFIT_DEPFILES+=${CONFIT_OBJ_ROOT}/${_src:R}.d
${_obj}: ${CONFIT_SOURCE_ROOT}/${_src}
	@mkdir -p -- ${.TARGET:H}
	${CONFIT_HOST_CC} ${CONFIT_STRICT_CFLAGS} ${CONFIT_INCLUDE_FLAGS} \
	    ${CONFIT_TEST_DEFINES} -MMD -MP -MF ${.TARGET:R}.d \
	    -c ${.ALLSRC} -o ${.TARGET}
${_bin}: ${_obj} ${CONFIT_PRODUCT_OBJECTS} ${CONFIT_TEST_SUPPORT_OBJECTS}
	@mkdir -p -- ${.TARGET:H}
	${CONFIT_HOST_CC} -o ${.TARGET} ${.ALLSRC} ${CONFIT_LINK_LIBS}
.endfor

${CONFIT_BINARY}: ${CONFIT_PRODUCT_OBJECTS} ${CONFIT_CLI_OBJECTS}
	@mkdir -p -- ${.TARGET:H}
	${CONFIT_HOST_CC} -o ${.TARGET} ${.ALLSRC} ${CONFIT_LINK_LIBS}

CONFIT_GENERATED_FILES= \
	${CONFIT_PRODUCT_OBJECTS} ${CONFIT_CLI_OBJECTS} \
	${CONFIT_TEST_SUPPORT_OBJECTS} ${CONFIT_TEST_OBJECTS} \
	${CONFIT_DEPFILES} ${CONFIT_BINARY} ${CONFIT_TEST_BINARIES}

.for _dep in ${CONFIT_DEPFILES}
.sinclude "${_dep}"
.endfor

.endif
