# Generated by Confit. Do not edit.
# This fragment is safe to include from a build tree.

set(CONFIT_PROJECT "parus")
set(CONFIT_PROFILE "qemu-aarch64")
set(CONFIT_TARGET "qemu-virt-aarch64")
set(CONFIT_VERSION "confit 0.1.0-round1")
set(CONFIT_SOURCE_HASH "0x922E8FF882EEEDB3")
set(CONFIT_OPTION_COUNT "33")

set(CONFIT_CONFIG_HEADER "${CMAKE_CURRENT_LIST_DIR}/config.h")
set(CONFIT_CONFIG_REPORT_JSON "${CMAKE_CURRENT_LIST_DIR}/config.report.json")
set(CONFIT_CONFIG_EXPLAIN_TXT "${CMAKE_CURRENT_LIST_DIR}/config.explain.txt")
set(CONFIT_CONFIG_GRAPH_JSON "${CMAKE_CURRENT_LIST_DIR}/config.graph.json")
set(CONFIT_CONFIG_INPUTS_JSON "${CMAKE_CURRENT_LIST_DIR}/config.inputs.json")

set(PARUS_CONFIG_HEADER "${CONFIT_CONFIG_HEADER}")
set(PARUS_CONFIG_SOURCE_HASH "${CONFIT_SOURCE_HASH}")
