/* Generated by Confit. Do not edit. */
/* project: delos */
/* profile: sim-dsh */
/* target: host-sim */
/* source hash: 0x9C11AEAD955DCA37 */

#ifndef DELOS_GENERATED_CONFIG_H
#define DELOS_GENERATED_CONFIG_H

#define DELOS_CONFIG_DEBUG_DDC 1
#define DELOS_CONFIG_INTERNAL_DEBUG_GATE 0
#define DELOS_CONFIG_MEMORY_FLASH_BASE 0x08000000U
#define DELOS_CONFIG_OUTPUT_NAME "delos-host-sim"
#define DELOS_CONFIG_PATHS_CONFIG_ROOT "build/generated/config/delos/sim-dsh"
#define DELOS_CONFIG_SCHEDULER_TASK_SLOTS 32U
#define DELOS_CONFIG_SIM_DEFAULT_GAIN 0.25
#define DELOS_CONFIG_TARGET_BOARD "host-sim"

#define DELOS_CONFIG_SOURCE_HASH 0x9C11AEAD955DCA37ULL

#endif /* DELOS_GENERATED_CONFIG_H */
